# Generated by Django 4.0.4 on 2022-06-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_pettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breedtype', models.CharField(max_length=50)),
                ('pettype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.pettype')),
            ],
        ),
    ]
