# Generated by Django 4.0.4 on 2022-06-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitaltype', models.CharField(max_length=50)),
            ],
        ),
    ]
