# Generated by Django 4.0.4 on 2022-06-08 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0006_newhospital_hospitaltype'),
        ('Admin', '0006_hospitaltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('image', models.FileField(max_length=50, upload_to='')),
                ('license', models.FileField(max_length=50, upload_to='')),
                ('details', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('doj', models.DateField(auto_now_add=True)),
                ('breedtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.breedtype')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newshop')),
            ],
        ),
    ]
