# Generated by Django 4.0.4 on 2022-06-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpets',
            name='name',
        ),
        migrations.AlterField(
            model_name='newpets',
            name='image',
            field=models.FileField(null=True, upload_to='Uploads/newpets/image/'),
        ),
        migrations.AlterField(
            model_name='newpets',
            name='license',
            field=models.FileField(null=True, upload_to='Uploads/newpets/license/'),
        ),
    ]
