# Generated by Django 4.0.4 on 2022-06-08 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_newhospital_hospitaltype'),
        ('Admin', '0006_hospitaltype'),
        ('Shop', '0002_remove_newpets_name_alter_newpets_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('image', models.FileField(null=True, upload_to='Uploads/newproducts/image/')),
                ('stock', models.CharField(max_length=50)),
                ('doj', models.DateField(auto_now_add=True)),
                ('breedtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.breedtype')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newshop')),
            ],
        ),
    ]
