# Generated by Django 4.0.4 on 2022-06-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_newfooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfooditem',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
