# Generated by Django 4.0.4 on 2022-06-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_newfooditem_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpets',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
