# Generated by Django 4.0.4 on 2022-06-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_feedbackshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackshop',
            old_name='user',
            new_name='shop',
        ),
    ]
