# Generated by Django 4.0.4 on 2022-06-22 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_alter_newshop_contact'),
        ('Shop', '0008_rename_user_feedbackshop_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainttitle', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=50)),
                ('attachment', models.FileField(upload_to='Uploads/attachmentshop/')),
                ('doj', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newshop')),
            ],
        ),
    ]
