# Generated by Django 4.0.4 on 2022-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_complaintshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintshop',
            name='reply',
            field=models.TextField(default='noreply', max_length=50),
        ),
    ]
