# Generated by Django 4.0.4 on 2022-06-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_complaintshop_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfooditem',
            name='fooditemdetails',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newproducts',
            name='productdetails',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
