# Generated by Django 4.0.4 on 2022-06-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_hospitaltype'),
        ('Guest', '0002_alter_newuser_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('address', models.TextField(max_length=50)),
                ('proof', models.FileField(upload_to='Uploads/newshopphotos/')),
                ('logo', models.ImageField(upload_to='Uploads/newshopphotos/')),
                ('password', models.CharField(max_length=50)),
                ('doj', models.DateField(auto_now_add=True)),
                ('vstatus', models.IntegerField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
