# Generated by Django 4.0.4 on 2022-06-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_newshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newshop',
            name='logo',
            field=models.ImageField(upload_to='Uploads/newshopphotos/logophotos/'),
        ),
        migrations.AlterField(
            model_name='newshop',
            name='proof',
            field=models.FileField(upload_to='Uploads/newshopphotos/proofphotos/'),
        ),
    ]
