# Generated by Django 4.0.4 on 2022-06-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_hospitaltype'),
        ('Guest', '0004_alter_newshop_logo_alter_newshop_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('address', models.TextField(max_length=50)),
                ('proof', models.FileField(upload_to='Uploads/newhospitalphotos/proofphotos/')),
                ('logo', models.FileField(upload_to='Uploads/newhospitalphotos/logophotos/')),
                ('password', models.CharField(max_length=50)),
                ('doj', models.DateField(auto_now_add=True)),
                ('vstatus', models.IntegerField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
