# Generated by Django 4.0.4 on 2022-06-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_hospitaltype'),
        ('Guest', '0005_newhospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='newhospital',
            name='hospitaltype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.hospitaltype'),
        ),
    ]
