# Generated by Django 4.0.4 on 2022-06-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_newhospital_hospitaltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newshop',
            name='contact',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
