# Generated by Django 4.0.4 on 2022-06-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_alter_newshop_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newshop',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
