# Generated by Django 4.0.4 on 2022-06-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_newshop_shopownercontact_newshop_shopownername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adminlogin',
        ),
    ]
