# Generated by Django 4.0.4 on 2022-06-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_hospitaltype'),
        ('Guest', '0006_newhospital_hospitaltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookeddate', models.DateField(auto_now_add=True)),
                ('quantity', models.CharField(max_length=50)),
                ('totalprice', models.CharField(max_length=50)),
                ('vstatus', models.IntegerField(default=False)),
                ('pstatus', models.IntegerField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.pettype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
