# Generated by Django 4.0.4 on 2022-06-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_newfooditem'),
        ('Guest', '0006_newhospital_hospitaltype'),
        ('User', '0002_alter_bookpet_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookeddate', models.DateField(auto_now_add=True)),
                ('quantity', models.CharField(max_length=50)),
                ('totalprice', models.CharField(max_length=50)),
                ('vstatus', models.IntegerField(default=False)),
                ('pstatus', models.IntegerField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.newproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
