# Generated by Django 4.0.4 on 2022-06-11 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_newhospital_hospitaltype'),
        ('Shop', '0004_newfooditem'),
        ('User', '0003_bookproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookeddate', models.DateField(auto_now_add=True)),
                ('quantity', models.CharField(max_length=50)),
                ('totalprice', models.CharField(max_length=50)),
                ('vstatus', models.IntegerField(default=False)),
                ('pstatus', models.IntegerField(default=False)),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.newfooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
