# Generated by Django 4.0.4 on 2022-06-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_newdoctor_qualification'),
        ('Guest', '0009_adminlogin'),
        ('User', '0006_complaintuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doj', models.DateField(auto_now_add=True)),
                ('bookingdate', models.DateTimeField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('consultationfee', models.CharField(max_length=50)),
                ('vstatus', models.IntegerField(default=False)),
                ('pstatus', models.IntegerField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.newdoctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
