# Generated by Django 4.0.4 on 2022-06-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_bookdoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdoctor',
            name='bookingtime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookdoctor',
            name='bookingdate',
            field=models.CharField(max_length=50),
        ),
    ]
