# Generated by Django 4.0.4 on 2022-06-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_delete_adminlogin'),
        ('User', '0008_bookdoctor_bookingtime_alter_bookdoctor_bookingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='complainttoshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainttitle', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=50)),
                ('reply', models.TextField(default='noreply', max_length=50)),
                ('attachment', models.FileField(upload_to='Uploads/attachmenttoshop/')),
                ('doj', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
