# Generated by Django 4.0.4 on 2022-06-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_delete_adminlogin'),
        ('User', '0009_complainttoshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainttoshop',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.newshop'),
        ),
    ]
