# Generated by Django 4.0.4 on 2022-06-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_delete_adminlogin'),
        ('User', '0010_complainttoshop_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complainttoshop',
            new_name='complainttoshop1',
        ),
    ]
