# Generated by Django 4.0.4 on 2022-07-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_delete_adminlogin'),
        ('Shop', '0012_alter_complaintshop_attachment'),
        ('User', '0011_rename_complainttoshop_complainttoshop1'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doj', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=False)),
                ('bookeddate', models.DateField(auto_now_add=True)),
                ('quantity', models.CharField(max_length=50)),
                ('totalprice', models.CharField(max_length=50)),
                ('reply', models.TextField(default='noreply', max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('attachment', models.FileField(upload_to='Uploads/returnpet/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.newproducts')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='feedbackusertoshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=50)),
                ('doj', models.DateField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
