# Generated by Django 4.0.5 on 2022-07-04 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='from_shop',
            new_name='from_doctor',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='to_shop',
            new_name='to_doctor',
        ),
    ]
