# Generated by Django 4.0.5 on 2022-07-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_rename_from_shop_chat_from_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfood',
            name='deliverydate',
            field=models.CharField(default='Not Declared', max_length=50),
        ),
    ]
