# Generated by Django 4.0.5 on 2022-07-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_bookfood_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpet',
            name='deliverydate',
            field=models.CharField(default='Not Declared', max_length=50),
        ),
        migrations.AddField(
            model_name='bookproduct',
            name='deliverydate',
            field=models.CharField(default='Not Declared', max_length=50),
        ),
    ]
