# Generated by Django 4.0.4 on 2022-06-11 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_hospitaltype'),
        ('Guest', '0006_newhospital_hospitaltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newdoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('address', models.TextField(max_length=50)),
                ('photo', models.FileField(upload_to='Uploads/newdoctorphotos/')),
                ('proof', models.FileField(upload_to='Uploads/newdoctorphotos/')),
                ('password', models.CharField(max_length=50)),
                ('doj', models.DateField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newhospital')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
