# Generated by Django 4.0.4 on 2022-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_complainthospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdoctor',
            name='qualification',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
