# Generated by Django 4.0.4 on 2022-06-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_complaintdoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdoctor',
            name='attachment',
            field=models.FileField(null=True, upload_to='Uploads/attachmentdoctor/'),
        ),
        migrations.AddField(
            model_name='complaintdoctor',
            name='reply',
            field=models.TextField(default='noreply', max_length=50, null=True),
        ),
    ]
